// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *About Us → Staff Details*
 */
export interface AboutUsDocumentDataStaffDetailsItem {
  /**
   * Name field in *About Us → Staff Details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.staff_details[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Designation field in *About Us → Staff Details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.staff_details[].designation
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  designation: prismic.KeyTextField;

  /**
   * Picture field in *About Us → Staff Details*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.staff_details[].picture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<never>;

  /**
   * Is Director? field in *About Us → Staff Details*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: about_us.staff_details[].is_director
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_director: prismic.BooleanField;
}

/**
 * Content for About Us documents
 */
interface AboutUsDocumentData {
  /**
   * Our Mission field in *About Us*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.our_mission
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  our_mission: prismic.RichTextField;

  /**
   * Director's Note field in *About Us*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.directors_note
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  directors_note: prismic.RichTextField;

  /**
   * Citizen Charter field in *About Us*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.citizen_charter
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  citizen_charter: prismic.LinkToMediaField;

  /**
   * RTI field in *About Us*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.rti
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  rti: prismic.LinkToMediaField;

  /**
   * Staff Details field in *About Us*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.staff_details[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  staff_details: prismic.GroupField<
    Simplify<AboutUsDocumentDataStaffDetailsItem>
  >;
}

/**
 * About Us document from Prismic
 *
 * - **API ID**: `about_us`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutUsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AboutUsDocumentData>,
    'about_us',
    Lang
  >;

/**
 * Item in *Notice → Attachments*
 */
export interface NoticeDocumentDataAttachmentsItem {
  /**
   * Attachment Title field in *Notice → Attachments*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Name of the attachment
   * - **API ID Path**: notice.attachments[].attachment_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  attachment_title: prismic.KeyTextField;

  /**
   * Document Link field in *Notice → Attachments*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Link to the document
   * - **API ID Path**: notice.attachments[].document_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  document_link: prismic.LinkToMediaField;
}

/**
 * Content for Notice documents
 */
interface NoticeDocumentData {
  /**
   * Type field in *Notice*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Type of notice
   * - **Default Value**: Announcements & Circulars
   * - **API ID Path**: notice.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<
    'Announcements & Circulars' | 'Public Notices',
    'filled'
  >;

  /**
   * Title field in *Notice*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title of the notice
   * - **API ID Path**: notice.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Date Time field in *Notice*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: notice.date_time
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  date_time: prismic.TimestampField;

  /**
   * Description field in *Notice*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description of the notice.
   * - **API ID Path**: notice.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Attachments field in *Notice*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: notice.attachments[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  attachments: prismic.GroupField<Simplify<NoticeDocumentDataAttachmentsItem>>;
}

/**
 * Notice document from Prismic
 *
 * - **API ID**: `notice`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NoticeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<NoticeDocumentData>, 'notice', Lang>;

/**
 * Item in *Settings → Address*
 */
export interface SettingsDocumentDataAddressItem {
  /**
   * Line 1 field in *Settings → Address*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Line 1 of the address
   * - **API ID Path**: settings.address[].line_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  line_1: prismic.KeyTextField;

  /**
   * Line 2 field in *Settings → Address*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Line 2 of the address
   * - **API ID Path**: settings.address[].line_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  line_2: prismic.KeyTextField;

  /**
   * Line 3 field in *Settings → Address*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Line 3 of the address
   * - **API ID Path**: settings.address[].line_3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  line_3: prismic.KeyTextField;

  /**
   * Maps Link field in *Settings → Address*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Link of the map. Ex: Google Maps
   * - **API ID Path**: settings.address[].maps_link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  maps_link: prismic.KeyTextField;
}

/**
 * Item in *Settings → Hero Slideshow Images*
 */
export interface SettingsDocumentDataHeroSlideshowImagesItem {
  /**
   * Image Link field in *Settings → Hero Slideshow Images*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Link to the image
   * - **API ID Path**: settings.hero_slideshow_images[].image_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image_link: prismic.LinkToMediaField;
}

/**
 * Item in *Settings → External Links*
 */
export interface SettingsDocumentDataExternalLinksItem {
  /**
   * Link Title field in *Settings → External Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.external_links[].link_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_title: prismic.KeyTextField;

  /**
   * Link URL field in *Settings → External Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.external_links[].link_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_url: prismic.LinkField;

  /**
   * Link Thumbnail field in *Settings → External Links*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.external_links[].link_thumbnail
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  link_thumbnail: prismic.ImageField<never>;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title of the website. This will be used for SEO as well as all over the website.
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Tagline field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Tagline of the brand. This will be used all over the website.
   * - **API ID Path**: settings.tagline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Description of the website. This will be used for SEO.
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Phone Number field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Contact Number For Contact Us Section
   * - **API ID Path**: settings.phone_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_number: prismic.KeyTextField;

  /**
   * Email field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Email for Contact Us Section
   * - **API ID Path**: settings.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Place field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Primary place of the brand (Ex: India)
   * - **API ID Path**: settings.place
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  place: prismic.KeyTextField;

  /**
   * Address field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.address[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  address: prismic.GroupField<Simplify<SettingsDocumentDataAddressItem>>;

  /**
   * Hero Info Banner field in *Settings*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Link to the information banner
   * - **API ID Path**: settings.hero_info_banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  hero_info_banner: prismic.LinkToMediaField;

  /**
   * Hero Slideshow Images field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.hero_slideshow_images[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  hero_slideshow_images: prismic.GroupField<
    Simplify<SettingsDocumentDataHeroSlideshowImagesItem>
  >;

  /**
   * External Links field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.external_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  external_links: prismic.GroupField<
    Simplify<SettingsDocumentDataExternalLinksItem>
  >;

  /**
   * Apply Now Form Link field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Form Link to apply
   * - **API ID Path**: settings.apply_now_form_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  apply_now_form_link: prismic.LinkField;

  /**
   * Contribution Payment Link field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contribution_payment_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  contribution_payment_link: prismic.LinkField;

  /**
   * Exam Payment Link field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.exam_payment_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  exam_payment_link: prismic.LinkField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    'settings',
    Lang
  >;

export type AllDocumentTypes =
  | AboutUsDocument
  | NoticeDocument
  | SettingsDocument;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutUsDocument,
      AboutUsDocumentData,
      AboutUsDocumentDataStaffDetailsItem,
      NoticeDocument,
      NoticeDocumentData,
      NoticeDocumentDataAttachmentsItem,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataAddressItem,
      SettingsDocumentDataHeroSlideshowImagesItem,
      SettingsDocumentDataExternalLinksItem,
      AllDocumentTypes,
    };
  }
}
